In [3]:
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# creating a dataframe from dictionary of list


data={
    'name':["suraj","sonu","madhur"],
    'age':[21,23,45],
    'city':["lucknow","delhi","kanpur"],
}
df=pd.DataFrame(data)
print(df)
print(type(df))

df

     name  age     city
0   suraj   21  lucknow
1    sonu   23    delhi
2  madhur   45   kanpur
<class 'pandas.core.frame.DataFrame'>

     name  age     city
0   suraj   21  lucknow
1    sonu   23    delhi
2  madhur   45   kanpur

In [8]:
import numpy as np
np.array(df)

array([['suraj', 21, 'lucknow'],
       ['sonu', 23, 'delhi'],
       ['madhur', 45, 'kanpur']], dtype=object)

In [18]:
import pandas as pd

df = pd.read_csv("../sale_data.csv")
print(df.head())

   Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum
2           10003  2024-01-03         Clothing         Levi's 501 Jeans
3           10004  2024-01-04            Books        The Da Vinci Code
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set

   Units Sold  Unit Price    Total
0         2.0      999.99  1999.98
1         1.0      499.99   499.99
2         3.0       69.99   209.97
3         4.0       14.99    59.96
4         2.0       29.99    59.98

In [20]:
# ACCESSING DATA FROM DATA FRAME
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2.0,999.99,1999.98
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1.0,499.99,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3.0,69.99,209.97
3,10004,2024-01-04,Books,The Da Vinci Code,4.0,14.99,59.96
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,2.0,29.99,59.98
5,10006,2024-01-06,Electronics,Samsung Galaxy S23,5.0,799.99,3999.95
6,10007,2024-01-07,Clothing,Nike Air Max,3.0,129.99,389.97
7,10008,2024-01-08,Books,Atomic Habits,6.0,18.99,113.94
8,10009,2024-01-09,Home Appliances,Philips Air Fryer,2.0,NaN,NaN
9,10010,2024-01-10,Electronics,Sony WH-1000XM5,4.0,349.99,1399.96
10,10011,2024-01-11,Beauty Products,Maybelline Makeup Kit,5.0,24.99,124.95
11,10012,2024-01-12,Clothing,Adidas Hoodie,3.0,59.99,179.97
12,10013,2024-01-13,Electronics,MacBook Air M2,1.0,1099.99,1099.99
13,10014,2024-01-14,Books,Harry Potter Book,7.0,12.99,90.93
14,10015,2024-01-15,Home Appliances,LG Microwave,2.0,199.99,399.98
15,10016,2024-01-16,Clothing,Zara Jacket,4.0,89.99,359.96
16,10017,2024-01-17,Beauty Products,Lakme Face Kit,3.0,34.99,104.97
17,10018,2024-01-18,Electronics,Apple iPad,NaN,449.99,NaN
18,10019,2024-01-19,Books,Rich Dad Poor Dad,5.0,16.99,84.95
19,10020,2024-01-20,Clothing,Puma Sneakers,4.0,79.99,319.96
20,10021,2024-01-21,Home Appliances,Samsung TV,1.0,699.99,699.99
21,10022,2024-01-22,Electronics,OnePlus 12,3.0,699.99,2099.97
22,10023,2024-01-23,Beauty Products,The Alchemist,6.0,13.99,83.94
23,10024,2024-01-24,Books,H&M T-Shirt,5.0,19.99,99.95
24,10025,2024-01-25,NaN,Levi's Denim Jacket,2.0,99.99,199.98
25,10026,2024-01-26,Electronics,Dell Inspiron Laptop,1.0,649.99,649.99
26,10027,2024-01-27,Home Appliances,Bajaj Mixer Grinder,3.0,59.99,179.97
27,10028,2024-01-28,Beauty Products,Nivea Body Lotion,4.0,22.99,91.96
28,10029,2024-01-29,Books,Ikigai,6.0,11.99,71.94
29,10030,2024-01-30,Electronics,JBL Bluetooth Speaker,2.0,89.99,179.98

In [23]:
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2.0,999.99,1999.98
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1.0,499.99,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3.0,69.99,209.97
3,10004,2024-01-04,Books,The Da Vinci Code,4.0,14.99,59.96
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,2.0,29.99,59.98

In [ ]:
type(df['Units Sold'])

pandas.core.series.Series

In [31]:
# TO ACCESS THE PARTICULAR ROW
df.loc[1]

Transaction ID                 10002
Date                      2024-01-02
Product Category     Home Appliances
Product Name        Dyson V11 Vacuum
Units Sold                       1.0
Unit Price                    499.99
Total                         499.99
Name: 1, dtype: object

In [30]:
df.iloc[1]

Transaction ID                 10002
Date                      2024-01-02
Product Category     Home Appliances
Product Name        Dyson V11 Vacuum
Units Sold                       1.0
Unit Price                    499.99
Total                         499.99
Name: 1, dtype: object

In [32]:
# ACCESSING SPECIFIED ELEMENTS 
df.at[1,"Product Name"]

'Dyson V11 Vacuum'

In [5]:
data={
    'name':["suraj","sonu","madhur"],
    'age':[21,23,45],
    'city':["lucknow","delhi","kanpur"],
}
df=pd.DataFrame(data)
print(df)
print(type(df))

df

     name  age     city
0   suraj   21  lucknow
1    sonu   23    delhi
2  madhur   45   kanpur
<class 'pandas.core.frame.DataFrame'>

     name  age     city
0   suraj   21  lucknow
1    sonu   23    delhi
2  madhur   45   kanpur

In [6]:
# ADDING COLUMN

df['city']=["mumbai","rajasthan","up"]
df['salary']=[20000,50000,10000 ]

df

     name  age       city  salary
0   suraj   21     mumbai   20000
1    sonu   23  rajasthan   50000
2  madhur   45         up   10000

In [7]:
# it does not remove column permanantly
df.drop('salary',axis=1)
df

     name  age       city  salary
0   suraj   21     mumbai   20000
1    sonu   23  rajasthan   50000
2  madhur   45         up   10000

In [10]:

# remove the row with index 2
# df.drop(2, axis=0)


# df.drop('salary',axis=1, inplace=True)
print(df)

     name  age       city
0   suraj   21     mumbai
1    sonu   23  rajasthan
2  madhur   45         up

In [12]:
# ADD AGE BY 10 FOR EXH COLUMN OF AGE
df['age']=df['age']+10
df

     name  age       city
0   suraj   31     mumbai
1    sonu   33  rajasthan
2  madhur   55         up

In [28]:
df['name']=['monu','suraj','golu']
df

ValueError: Length of values (3) does not match length of index (2)

In [31]:
df.drop(0,axis=0)

df

    name  age       city
0   monu   31     mumbai
1  suraj   33  rajasthan

In [ ]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("\nStatistical summary:\n", df.describe())

# Group by a column and calculate mean
# grouped = df.groupby('city')['age'].mean()

# print(grouped)

Data types:
 name    object
age      int64
city    object
dtype: object

Statistical summary:
              age
count   2.000000
mean   32.000000
std     1.414214
min    31.000000
25%    31.500000
50%    32.000000
75%    32.500000
max    33.000000
city
mumbai       31.0
rajasthan    33.0
Name: age, dtype: float64

In [35]:
grouped = df.groupby('city')['age'].mean()

print(grouped)

city
mumbai       31.0
rajasthan    33.0
Name: age, dtype: float64

In [36]:
df.describe()

             age
count   2.000000
mean   32.000000
std     1.414214
min    31.000000
25%    31.500000
50%    32.000000
75%    32.500000
max    33.000000

In [6]:
import pandas as pd
from io import StringIO

Data = '{"employee_name":"James", "email":"james@gmail.com", "job_profile":[{"title1":"Team Lead"}]}'

# pd.read_json(StringIO(Data))
df.to_json()

'{"name":{"0":"suraj","1":"sonu","2":"madhur"},"age":{"0":21,"1":23,"2":45},"city":{"0":"lucknow","1":"delhi","2":"kanpur"}}'

In [17]:
!pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Collecting lxml
  Downloading lxml-6.1.3-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Downloading lxml-6.1.3-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 7.3 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 9.9 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.3

[notice] A new release of pip is available: 26.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
!pip install html5lib

Defaulting to user installation because normal site-packages is not writeable
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in C:\Users\Suraj  Pandey\AppData\Roaming\Python\Python313\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.6.1-py3-none-any.whl.metadata (3.4 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.6.1-py3-none-any.whl (8.7 kB)
Installing collected packages: webencodings, html5lib

   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   ---------------------------------------- 2/2 [html5lib]

Successfully installed html5lib-1.1 webencodings-0.6.1

[notice] A new release of pip is available: 26.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
url="https://www.fdic.gov/bank-failures/failed-bank-list"
df=pd.read_html(url)
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
5,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
6,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
7,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
8,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
9,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
10,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
11,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
12,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
13,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
14,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
15,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
16,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
17,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
18,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
19,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
20,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
21,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
22,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
23,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
24,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528

HTTPError: HTTP Error 403: Forbidden

In [27]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
df_excell=pd.read_excel("../sample_people.xlsx")

In [32]:
df_excell.to_pickle('df_excell')

In [33]:
pd.read_pickle('df_excell')

    Name  Age
0  Krist   32
1   Jack   34
2   John   31